### ISSUE TITLE
Black or white box attacks?

### ISSUE THREAD

**Issue by shenkev** [jaesik817/adv_attack_capsnet#1]
Are the attacks reported on the frontpage black-box or white-box? In other words, what are the 

(adversarial image producing model, testing model)

pairs for each attack?

**Comment by jsikyoon** [comment]
Hi @shenkev ,

Everyattack is white-box.

**Comment by jsikyoon** [comment]
if you don't have any other issues, then I will close this issue :)

**Comment by shenkev** [comment]
Nope, please close the issue. But have you tried black-box attacks as well? They hinted in their EM routing paper that capsules are not more robust to black-box than CNN's. This suggests  that it's simply hard to create adv. examples using capsule but ones created using other architectures work just as well on capsules. Therefore capsules aren't actually robust.

**Comment by jsikyoon** [comment]
I will do black-box attacks generated with naiive model.

**Comment by shenkev** [comment]
Quick question, for

Adversarial Training with adversarial examples from FGSM and Basic iter.

What was the training procedure? How many adversarial examples did the model get to train on? How many regular images did it train on?

**Comment by jsikyoon** [comment]
training procedure is same to naiive model, and the the number of adv. examples used on training is same to the number of training dataset.
