### ISSUE TITLE
Is this implementing Matrix Capsules with EM Routing?

### ISSUE THREAD

**Issue by Chillee** [jaesik817/adv_attack_capsnet#4]
I took a quick look at your code and it doesn't seem like it, but I wasn't sure.

I think it'd be interesting to try that, as quoting from its abstract: "Capsules also show far more resistance to white box adversarial attack than our baseline convolutional neural
network."

**Comment by jsikyoon** [comment]
no. this implementation is based on NIPS 2017 Caps. Net structure and https://github.com/InnerPeace-Wu/CapsNet-tensorflow. 

The paper you mentioned is quite interesting. I will check that. Thanks!

**Comment by Chillee** [comment]
Thanks! I took a quick look at your implementation, and that's what I thought. Just thought that since it specifically mentions a resistance to adversarial attacks it would be interesting to get more results.
