### ISSUE TITLE
RGB dataset (224*224)

### ISSUE THREAD

**Issue by redhat12345** [jaesik817/adv_attack_capsnet#5]
How can we use ur code in other RGB dataset?
Suppose the structure of dataset is like that. it contains some sub-folder. Each sub-folder represents one class.

Class A:
0001.jpg 1
0002.jpg 1
Class B:
0001.jpg 2
0002.jpg 2

**Comment by jsikyoon** [comment]
hi,

CapsNet in this repo has conv layer on front of input, thus I think you can easily use RGB imgs on there with change of conv layer option.

Thanks.

BRs, Jaesik.
